[package]
name = "route_verification_io"
version = "0.1.2"
edition = "2021"

description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
