[workspace]
members = ["bgp", "bloom", "io", "irr", "lex", "parse"]

[package]
name = "route_verification"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chardetng = "0.1.17"
encoding_rs = "0.8.32"
encoding_rs_io = "0.1.7"
env_logger = "0.10"
log = "0.4"
rayon = "1.7"

bgp = { package = "route_verification_bgp", path = "./bgp" }
bloom = { package = "route_verification_bloom", path = "./bloom" }
io = { package = "route_verification_io", path = "./io" }
irr = { package = "route_verification_irr", path = "./irr" }
lex = { package = "route_verification_lex", path = "./lex" }
parse = { package = "route_verification_parse", path = "./parse" }

[dev-dependencies]
dashmap = "5.5.0"
itertools = "0.11"
net-literals = "0.2.0"
polars = { version = "0.31", features = ["describe"] }
