from scripts import CsvFile

as_neighbors_vs_rules = CsvFile(
    "as_neighbors_vs_rules4.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13895627/as_neighbors_vs_rules4.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/pull/120>."""
as_pair_stats = CsvFile(
    "all3/route-views2--as_pair_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--as_pair_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""
as_stats = CsvFile(
    "all3/route-views2--as_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--as_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""
route_stats = CsvFile(
    "all3/route-views2--route_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--route_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""

as_stats_all = [
    CsvFile(
        "all3/oix-route-views--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/oix-route-views--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/pacwave.lax--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/pacwave.lax--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.amsix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.amsix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bdix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bdix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bknix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bknix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chicago--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chicago--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chile--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chile--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.decix-jhb--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.decix-jhb--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.eqix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.eqix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.flix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.flix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.fortaleza--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.fortaleza--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gixa--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gixa--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gorex--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gorex--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.isc--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.isc--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.kixp--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.kixp--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.linx--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.linx--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.mwix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.mwix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.napafrica--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.napafrica--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.nwax--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.nwax--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.ny--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.ny--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.perth--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.perth--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.peru--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.peru--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.phoix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.phoix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.rio--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.rio--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sfmix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sfmix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sg--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sg--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.soxrs--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.soxrs--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sydney--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sydney--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.telxatl--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.telxatl--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.uaeix--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.uaeix--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.wide--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.wide--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2.saopaulo--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2.saopaulo--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views3--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views3--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views4--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views4--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views5--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views5--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views6--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views6--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc00--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc00--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc01--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc01--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc03--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc03--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc04--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc04--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc05--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc05--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc06--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc06--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc07--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc07--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc10--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc10--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc11--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc11--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc12--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc12--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc13--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc13--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc14--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc14--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc15--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc15--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc16--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc16--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc18--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc18--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc19--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc19--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc20--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc20--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc21--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc21--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc22--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc22--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc23--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc23--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc24--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc24--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc25--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc25--as_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc26--as_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc26--as_stats3.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""

as_pair_stats_all = [
    CsvFile(
        "all3/oix-route-views--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/oix-route-views--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/pacwave.lax--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/pacwave.lax--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.amsix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.amsix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bdix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bdix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bknix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bknix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chicago--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chicago--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chile--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chile--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.decix-jhb--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.decix-jhb--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.eqix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.eqix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.flix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.flix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.fortaleza--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.fortaleza--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gixa--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gixa--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gorex--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gorex--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.isc--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.isc--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.kixp--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.kixp--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.linx--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.linx--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.mwix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.mwix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.napafrica--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.napafrica--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.nwax--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.nwax--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.ny--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.ny--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.perth--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.perth--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.peru--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.peru--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.phoix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.phoix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.rio--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.rio--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sfmix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sfmix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sg--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sg--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.soxrs--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.soxrs--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sydney--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sydney--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.telxatl--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.telxatl--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.uaeix--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.uaeix--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.wide--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.wide--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2.saopaulo--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2.saopaulo--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views3--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views3--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views4--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views4--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views5--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views5--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views6--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views6--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc00--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc00--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc01--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc01--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc03--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc03--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc04--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc04--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc05--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc05--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc06--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc06--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc07--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc07--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc10--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc10--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc11--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc11--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc12--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc12--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc13--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc13--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc14--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc14--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc15--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc15--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc16--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc16--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc18--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc18--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc19--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc19--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc20--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc20--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc21--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc21--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc22--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc22--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc23--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc23--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc24--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc24--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc25--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc25--as_pair_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc26--as_pair_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc26--as_pair_stats3.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""

route_stats_all = [
    CsvFile(
        "all3/oix-route-views--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/oix-route-views--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/pacwave.lax--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/pacwave.lax--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.amsix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.amsix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bdix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bdix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bknix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bknix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chicago--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chicago--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chile--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chile--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.decix-jhb--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.decix-jhb--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.eqix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.eqix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.flix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.flix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.fortaleza--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.fortaleza--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gixa--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gixa--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gorex--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gorex--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.isc--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.isc--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.kixp--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.kixp--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.linx--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.linx--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.mwix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.mwix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.napafrica--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.napafrica--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.nwax--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.nwax--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.ny--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.ny--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.perth--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.perth--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.peru--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.peru--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.phoix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.phoix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.rio--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.rio--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sfmix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sfmix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sg--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sg--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.soxrs--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.soxrs--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sydney--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sydney--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.telxatl--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.telxatl--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.uaeix--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.uaeix--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.wide--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.wide--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2.saopaulo--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2.saopaulo--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views3--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views3--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views4--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views4--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views5--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views5--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views6--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views6--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc00--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc00--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc01--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc01--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc03--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc03--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc04--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc04--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc05--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc05--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc06--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc06--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc07--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc07--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc10--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc10--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc11--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc11--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc12--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc12--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc13--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc13--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc14--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc14--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc15--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc15--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc16--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc16--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc18--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc18--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc19--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc19--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc20--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc20--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc21--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc21--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc22--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc22--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc23--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc23--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc24--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc24--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc25--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc25--route_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc26--route_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc26--route_stats3.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""

route_first_hop_stats_all = [
    CsvFile(
        "all3/oix-route-views--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/oix-route-views--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/pacwave.lax--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/pacwave.lax--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.amsix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.amsix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bdix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bdix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.bknix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.bknix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chicago--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chicago--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.chile--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.chile--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.decix-jhb--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.decix-jhb--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.eqix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.eqix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.flix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.flix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.fortaleza--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.fortaleza--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gixa--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gixa--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.gorex--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.gorex--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.isc--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.isc--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.kixp--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.kixp--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.linx--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.linx--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.mwix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.mwix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.napafrica--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.napafrica--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.nwax--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.nwax--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.ny--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.ny--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.perth--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.perth--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.peru--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.peru--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.phoix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.phoix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.rio--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.rio--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sfmix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sfmix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sg--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sg--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.soxrs--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.soxrs--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.sydney--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.sydney--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.telxatl--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.telxatl--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.uaeix--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.uaeix--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views.wide--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views.wide--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views2.saopaulo--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views2.saopaulo--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views3--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views3--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views4--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views4--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views5--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views5--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/route-views6--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/route-views6--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc00--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc00--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc01--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc01--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc03--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc03--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc04--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc04--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc05--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc05--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc06--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc06--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc07--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc07--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc10--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc10--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc11--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc11--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc12--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc12--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc13--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc13--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc14--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc14--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc15--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc15--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc16--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc16--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc18--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc18--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc19--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc19--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc20--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc20--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc21--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc21--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc22--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc22--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc23--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc23--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc24--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc24--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc25--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc25--route_first_hop_stats3.csv.gz",
    ),
    CsvFile(
        "all3/rrc26--route_first_hop_stats3.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-142-follow-up/rrc26--route_first_hop_stats3.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-142-follow-up>."""

route_all_import_stats = CsvFile(
    "all3/route_all_import_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/14846212/route_all_import_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142#issuecomment-2033452390>."""
route_all_export_stats = CsvFile(
    "all3/route_all_export_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/14846211/route_all_export_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142#issuecomment-2033452390>."""
route_all_total_stats = CsvFile(
    "all3/route_all_total_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/14846213/route_all_total_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142#issuecomment-2033452390>."""

route_first_hop_all_import_stats = CsvFile(
    "all3/route_first_hop_all_import_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/15039597/route_first_hop_all_import_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/141#issuecomment-2066378668>."""
route_first_hop_all_export_stats = CsvFile(
    "all3/route_first_hop_all_export_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/15039596/route_first_hop_all_export_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/141#issuecomment-2066378668>."""
route_first_hop_all_total_stats = CsvFile(
    "all3/route_first_hop_all_total_stats3.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/15039598/route_first_hop_all_total_stats3.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/141#issuecomment-2066378668>."""

as_set_sizes = CsvFile(
    "as_set_sizes2.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/13885027/as_set_sizes2.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/114>."""

as_set_graph_stats = CsvFile(
    "as_set_graph_stats.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14004282/as_set_graph_stats.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/114>."""

as_num_appearances_in_rules = CsvFile(
    "as_num_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124410/as_num_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

as_set_appearances_in_rules = CsvFile(
    "as_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124411/as_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

filter_set_appearances_in_rules = CsvFile(
    "filter_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124421/filter_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

peering_set_appearances_in_rules = CsvFile(
    "peering_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124422/peering_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

route_set_appearances_in_rules = CsvFile(
    "route_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124425/route_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

transit_as_stats = CsvFile(
    "transit_as_stats2.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14917813/transit_as_stats2.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/134#issuecomment-2028748974>."""

as_compatible_with_bgpq3 = CsvFile(
    "as_compatible_with_bgpq3.csv",
    "https://github.com/SichangHe/internet_route_verification/files/12906608/as_compatible_with_bgpq3.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/64>."""

route_objects_defined_multiple_times = CsvFile(
    "route_objects_defined_multiple_times.json.gz",
    "https://github.com/SichangHe/internet_route_verification/files/14734281/route_objects_defined_multiple_times.json.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/138#issuecomment-2016682503>.
Not a CSV file, but a similar JSON file."""

last_modified = CsvFile(
    "last_modified.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/releases/download/data-130/last_modified.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/130>."""

bgpq3_compatible_rules = CsvFile(
    "bgpq3_compatible_rules.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/15190015/bgpq3_compatible_rules.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/137#issuecomment-2090699322>."""
