from scripts import CsvFile

as_neighbors_vs_rules = CsvFile(
    "as_neighbors_vs_rules4.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13895627/as_neighbors_vs_rules4.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/pull/120>."""
as_pair_stats = CsvFile(
    "all3/route-views2--as_pair_stats3.csv.gz",
    "TODO",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142>."""
as_stats = CsvFile(
    "all3/route-views2--as_stats3.csv.gz",
    "TODO",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142>."""
route_stats = CsvFile(
    "all3/route-views2--route_stats3.csv.gz",
    "TODO",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142>."""

as_stats_all = [
    CsvFile(
        "all2/oix-route-views--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/oix-route-views--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/pacwave.lax--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/pacwave.lax--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.amsix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.amsix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bdix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bdix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bknix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bknix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chicago--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chicago--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chile--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chile--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.decix-jhb--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.decix-jhb--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.eqix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.eqix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.flix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.flix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.fortaleza--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.fortaleza--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gixa--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gixa--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gorex--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gorex--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.isc--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.isc--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.kixp--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.kixp--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.linx--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.linx--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.mwix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.mwix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.napafrica--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.napafrica--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.nwax--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.nwax--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.ny--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.ny--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.perth--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.perth--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.peru--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.peru--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.phoix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.phoix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.rio--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.rio--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sfmix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sfmix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sg--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sg--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.soxrs--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.soxrs--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sydney--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sydney--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.telxatl--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.telxatl--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.uaeix--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.uaeix--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.wide--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.wide--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2.saopaulo--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2.saopaulo--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views3--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views3--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views4--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views4--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views5--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views5--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views6--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views6--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc00--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc00--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc01--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc01--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc03--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc03--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc04--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc04--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc05--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc05--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc06--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc06--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc07--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc07--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc10--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc10--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc11--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc11--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc12--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc12--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc13--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc13--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc14--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc14--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc15--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc15--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc16--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc16--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc18--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc18--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc19--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc19--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc20--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc20--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc21--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc21--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc22--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc22--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc23--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc23--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc24--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc24--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc25--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc25--as_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc26--as_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc26--as_stats2.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-141-142>."""

as_pair_stats_all = [
    CsvFile(
        "all2/oix-route-views--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/oix-route-views--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/pacwave.lax--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/pacwave.lax--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.amsix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.amsix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bdix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bdix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bknix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bknix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chicago--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chicago--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chile--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chile--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.decix-jhb--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.decix-jhb--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.eqix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.eqix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.flix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.flix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.fortaleza--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.fortaleza--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gixa--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gixa--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gorex--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gorex--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.isc--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.isc--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.kixp--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.kixp--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.linx--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.linx--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.mwix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.mwix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.napafrica--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.napafrica--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.nwax--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.nwax--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.ny--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.ny--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.perth--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.perth--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.peru--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.peru--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.phoix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.phoix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.rio--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.rio--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sfmix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sfmix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sg--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sg--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.soxrs--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.soxrs--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sydney--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sydney--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.telxatl--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.telxatl--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.uaeix--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.uaeix--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.wide--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.wide--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2.saopaulo--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2.saopaulo--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views3--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views3--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views4--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views4--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views5--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views5--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views6--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views6--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc00--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc00--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc01--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc01--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc03--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc03--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc04--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc04--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc05--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc05--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc06--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc06--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc07--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc07--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc10--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc10--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc11--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc11--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc12--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc12--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc13--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc13--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc14--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc14--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc15--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc15--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc16--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc16--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc18--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc18--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc19--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc19--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc20--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc20--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc21--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc21--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc22--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc22--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc23--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc23--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc24--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc24--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc25--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc25--as_pair_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc26--as_pair_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc26--as_pair_stats2.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-141-142>."""

route_stats_all = [
    CsvFile(
        "all2/oix-route-views--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/oix-route-views--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/pacwave.lax--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/pacwave.lax--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.amsix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.amsix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bdix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bdix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bknix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bknix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chicago--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chicago--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chile--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chile--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.decix-jhb--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.decix-jhb--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.eqix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.eqix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.flix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.flix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.fortaleza--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.fortaleza--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gixa--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gixa--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gorex--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gorex--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.isc--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.isc--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.kixp--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.kixp--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.linx--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.linx--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.mwix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.mwix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.napafrica--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.napafrica--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.nwax--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.nwax--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.ny--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.ny--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.perth--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.perth--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.peru--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.peru--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.phoix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.phoix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.rio--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.rio--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sfmix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sfmix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sg--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sg--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.soxrs--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.soxrs--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sydney--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sydney--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.telxatl--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.telxatl--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.uaeix--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.uaeix--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.wide--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.wide--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2.saopaulo--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2.saopaulo--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views3--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views3--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views4--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views4--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views5--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views5--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views6--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views6--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc00--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc00--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc01--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc01--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc03--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc03--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc04--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc04--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc05--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc05--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc06--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc06--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc07--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc07--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc10--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc10--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc11--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc11--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc12--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc12--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc13--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc13--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc14--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc14--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc15--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc15--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc16--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc16--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc18--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc18--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc19--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc19--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc20--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc20--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc21--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc21--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc22--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc22--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc23--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc23--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc24--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc24--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc25--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc25--route_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc26--route_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc26--route_stats2.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-141-142>."""

route_first_hop_stats_all = [
    CsvFile(
        "all2/oix-route-views--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/oix-route-views--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/pacwave.lax--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/pacwave.lax--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.amsix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.amsix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bdix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bdix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.bknix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.bknix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chicago--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chicago--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.chile--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.chile--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.decix-jhb--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.decix-jhb--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.eqix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.eqix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.flix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.flix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.fortaleza--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.fortaleza--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gixa--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gixa--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.gorex--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.gorex--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.isc--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.isc--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.kixp--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.kixp--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.linx--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.linx--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.mwix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.mwix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.napafrica--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.napafrica--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.nwax--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.nwax--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.ny--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.ny--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.perth--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.perth--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.peru--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.peru--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.phoix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.phoix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.rio--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.rio--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sfmix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sfmix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sg--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sg--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.soxrs--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.soxrs--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.sydney--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.sydney--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.telxatl--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.telxatl--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.uaeix--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.uaeix--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views.wide--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views.wide--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views2.saopaulo--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views2.saopaulo--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views3--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views3--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views4--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views4--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views5--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views5--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/route-views6--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/route-views6--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc00--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc00--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc01--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc01--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc03--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc03--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc04--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc04--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc05--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc05--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc06--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc06--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc07--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc07--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc10--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc10--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc11--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc11--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc12--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc12--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc13--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc13--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc14--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc14--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc15--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc15--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc16--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc16--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc18--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc18--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc19--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc19--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc20--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc20--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc21--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc21--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc22--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc22--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc23--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc23--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc24--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc24--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc25--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc25--route_first_hop_stats2.csv.gz",
    ),
    CsvFile(
        "all2/rrc26--route_first_hop_stats2.csv.gz",
        "/SichangHe/internet_route_verification/releases/download/data-141-142/rrc26--route_first_hop_stats2.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/releases/tag/data-141-142>."""

route_all_import_stats = CsvFile(
    "route_all_import_stats1.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13926591/route_all_total_stats1.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/88>."""
route_all_export_stats = CsvFile(
    "route_all_export_stats1.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13926592/route_all_export_stats1.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/88>."""
route_all_total_stats = CsvFile(
    "route_all_total_stats1.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13926593/route_all_import_stats1.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/88>."""

as_set_sizes = CsvFile(
    "as_set_sizes2.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/13885027/as_set_sizes2.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/114>."""

as_set_graph_stats = CsvFile(
    "as_set_graph_stats.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14004282/as_set_graph_stats.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/114>."""

as_num_appearances_in_rules = CsvFile(
    "as_num_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124410/as_num_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

as_set_appearances_in_rules = CsvFile(
    "as_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124411/as_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

filter_set_appearances_in_rules = CsvFile(
    "filter_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124421/filter_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

peering_set_appearances_in_rules = CsvFile(
    "peering_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124422/peering_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

route_set_appearances_in_rules = CsvFile(
    "route_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124425/route_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

transit_as_stats = CsvFile(
    "transit_as_stats.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14816185/transit_as_stats.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/134#issuecomment-2028748974>."""
