from scripts import CsvFile

as_neighbors_vs_rules = CsvFile(
    "as_neighbors_vs_rules4.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13895627/as_neighbors_vs_rules4.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/pull/120>."""
as_pair_stats = CsvFile(
    "as_pair_stats4.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/13884363/as_pair_stats4.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/pull/120>."""
as_stats = CsvFile(
    "as_stats4.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13884360/as_stats4.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/pull/120>."""
route_stats = CsvFile(
    "route_stats5.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/releases/download/data-142/route_stats5.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/142>."""

as_stats_all = [
    CsvFile(
        "pacwave.lax--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/pacwave.lax--as_stats1.csv",
    ),
    CsvFile(
        "route-views.amsix--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.amsix--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.bdix--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.bdix--as_stats1.csv",
    ),
    CsvFile(
        "route-views.bknix--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.bknix--as_stats1.csv",
    ),
    CsvFile(
        "route-views.chicago--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.chicago--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.chile--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.chile--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.decix-jhb--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.decix-jhb--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.eqix--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.eqix--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.flix--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.flix--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.fortaleza--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.fortaleza--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.gixa--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.gixa--as_stats1.csv",
    ),
    CsvFile(
        "route-views.gorex--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.gorex--as_stats1.csv",
    ),
    CsvFile(
        "route-views.isc--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.isc--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.kixp--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.kixp--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.linx--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.linx--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.mwix--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.mwix--as_stats1.csv",
    ),
    CsvFile(
        "route-views.napafrica--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.napafrica--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.nwax--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.nwax--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.ny--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.ny--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.perth--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.perth--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.peru--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.peru--as_stats1.csv",
    ),
    CsvFile(
        "route-views.phoix--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.phoix--as_stats1.csv",
    ),
    CsvFile(
        "route-views.rio--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.rio--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sfmix--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sfmix--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sg--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sg--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.soxrs--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.soxrs--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sydney--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sydney--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.telxatl--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.telxatl--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.uaeix--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.uaeix--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.wide--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.wide--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views2--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views2--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views2.saopaulo--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views2.saopaulo--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views3--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views3--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views4--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views4--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views5--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views5--as_stats1.csv.gz",
    ),
    CsvFile(
        "route-views6--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views6--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc00--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc00--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc01--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc01--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc03--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc03--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc04--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc04--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc05--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc05--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc06--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc06--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc07--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc07--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc10--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc10--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc11--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc11--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc12--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc12--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc13--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc13--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc14--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc14--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc15--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc15--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc16--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc16--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc18--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc18--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc19--as_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc19--as_stats1.csv",
    ),
    CsvFile(
        "rrc20--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc20--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc21--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc21--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc22--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc22--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc23--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc23--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc24--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc24--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc25--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc25--as_stats1.csv.gz",
    ),
    CsvFile(
        "rrc26--as_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc26--as_stats1.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/issues/116>."""

as_pair_stats_all = [
    CsvFile(
        "pacwave.lax--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/pacwave.lax--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.amsix--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.amsix--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.bdix--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.bdix--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.bknix--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.bknix--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.chicago--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.chicago--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.chile--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.chile--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.decix-jhb--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.decix-jhb--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.eqix--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.eqix--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.flix--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.flix--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.fortaleza--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.fortaleza--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.gixa--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.gixa--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.gorex--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.gorex--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.isc--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.isc--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.kixp--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.kixp--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.linx--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.linx--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.mwix--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.mwix--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.napafrica--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.napafrica--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.nwax--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.nwax--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.ny--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.ny--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.perth--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.perth--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.peru--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.peru--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.phoix--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.phoix--as_pair_stats1.csv",
    ),
    CsvFile(
        "route-views.rio--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.rio--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sfmix--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sfmix--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sg--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sg--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.soxrs--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.soxrs--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sydney--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sydney--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.telxatl--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.telxatl--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.uaeix--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.uaeix--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.wide--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.wide--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views2--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views2--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views2.saopaulo--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views2.saopaulo--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views3--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views3--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views4--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views4--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views5--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views5--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "route-views6--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views6--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc00--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc00--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc01--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc01--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc03--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc03--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc04--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc04--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc05--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc05--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc06--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc06--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc07--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc07--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc10--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc10--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc11--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc11--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc12--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc12--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc13--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc13--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc14--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc14--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc15--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc15--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc16--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc16--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc18--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc18--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc19--as_pair_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc19--as_pair_stats1.csv",
    ),
    CsvFile(
        "rrc20--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc20--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc21--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc21--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc22--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc22--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc23--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc23--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc24--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc24--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc25--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc25--as_pair_stats1.csv.gz",
    ),
    CsvFile(
        "rrc26--as_pair_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc26--as_pair_stats1.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/issues/116>."""

route_stats_all = [
    CsvFile(
        "pacwave.lax--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/pacwave.lax--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.amsix--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.amsix--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.bdix--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.bdix--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.bknix--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.bknix--route_stats1.csv",
    ),
    CsvFile(
        "route-views.chicago--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.chicago--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.chile--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.chile--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.decix-jhb--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.decix-jhb--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.eqix--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.eqix--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.flix--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.flix--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.fortaleza--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.fortaleza--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.gixa--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.gixa--route_stats1.csv",
    ),
    CsvFile(
        "route-views.gorex--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.gorex--route_stats1.csv",
    ),
    CsvFile(
        "route-views.isc--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.isc--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.kixp--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.kixp--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.linx--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.linx--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.mwix--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.mwix--route_stats1.csv",
    ),
    CsvFile(
        "route-views.napafrica--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.napafrica--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.nwax--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.nwax--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.ny--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.ny--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.perth--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.perth--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.peru--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.peru--route_stats1.csv",
    ),
    CsvFile(
        "route-views.phoix--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.phoix--route_stats1.csv",
    ),
    CsvFile(
        "route-views.rio--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.rio--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sfmix--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sfmix--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sg--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sg--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.soxrs--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.soxrs--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.sydney--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.sydney--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.telxatl--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.telxatl--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.uaeix--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.uaeix--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views.wide--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views.wide--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views2--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views2--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views2.saopaulo--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views2.saopaulo--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views3--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views3--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views4--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views4--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views5--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views5--route_stats1.csv.gz",
    ),
    CsvFile(
        "route-views6--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/route-views6--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc00--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc00--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc01--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc01--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc03--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc03--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc04--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc04--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc05--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc05--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc06--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc06--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc07--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc07--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc10--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc10--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc11--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc11--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc12--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc12--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc13--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc13--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc14--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc14--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc15--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc15--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc16--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc16--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc18--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc18--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc19--route_stats1.csv",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc19--route_stats1.csv",
    ),
    CsvFile(
        "rrc20--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc20--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc21--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc21--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc22--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc22--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc23--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc23--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc24--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc24--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc25--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc25--route_stats1.csv.gz",
    ),
    CsvFile(
        "rrc26--route_stats1.csv.gz",
        "https://github.com/SichangHe/internet_route_verification/releases/download/data-116-1/rrc26--route_stats1.csv.gz",
    ),
]
"""From <https://github.com/SichangHe/internet_route_verification/issues/116>."""

route_all_import_stats = CsvFile(
    "route_all_import_stats1.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13926591/route_all_total_stats1.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/88>."""
route_all_export_stats = CsvFile(
    "route_all_export_stats1.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13926592/route_all_export_stats1.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/88>."""
route_all_total_stats = CsvFile(
    "route_all_total_stats1.csv",
    "https://github.com/SichangHe/internet_route_verification/files/13926593/route_all_import_stats1.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/88>."""

as_set_sizes = CsvFile(
    "as_set_sizes2.csv.gz",
    "https://github.com/SichangHe/internet_route_verification/files/13885027/as_set_sizes2.csv.gz",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/114>."""

as_set_graph_stats = CsvFile(
    "as_set_graph_stats.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14004282/as_set_graph_stats.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/114>."""

as_num_appearances_in_rules = CsvFile(
    "as_num_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124410/as_num_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

as_set_appearances_in_rules = CsvFile(
    "as_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124411/as_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

filter_set_appearances_in_rules = CsvFile(
    "filter_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124421/filter_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

peering_set_appearances_in_rules = CsvFile(
    "peering_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124422/peering_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

route_set_appearances_in_rules = CsvFile(
    "route_set_appearances_in_rules.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14124425/route_set_appearances_in_rules.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/123>"""

transit_as_stats = CsvFile(
    "transit_as_stats.csv",
    "https://github.com/SichangHe/internet_route_verification/files/14816185/transit_as_stats.csv",
)
"""From <https://github.com/SichangHe/internet_route_verification/issues/134#issuecomment-2028748974>."""
