[package]
name = "route_verification_common_regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.31"
lazy-regex = "3.0"
once_cell = "1.18.0"
