[package]
name = "route_verification_bgp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dashmap = "5.5"
hashbrown = "0.14"
ipnet = { version = "2.8", features = ["serde"] }
lazy-regex = "3.0"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

map = { package = "route_verification_bgpmap", path = "../bgpmap" }
bloom = { package = "route_verification_bloom", path = "../bloom" }
io = { package = "route_verification_io", path = "../io" }
lex = { package = "route_verification_lex", path = "../lex" }
parse = { package = "route_verification_parse", path = "../parse" }

[dev-dependencies]
maplit = "1.0.2"
