[package]
name = "route_verification_bloom"
version = "0.1.1"
edition = "2021"

description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bit-vec.workspace = true
hashbrown = { workspace = true, features = ["raw"] }
