[package]
name = "route_verification_as_rel"
version = "0.1.2"
edition = "2021"

description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bzip2.workspace = true
hashbrown.workspace = true
log.workspace = true
