use std::net::{Ipv4Addr, Ipv6Addr};

use ipnet::*;

use crate::parse::*;

use super::*;

pub const RECURSION_LIMIT: isize = 0x100;

/// All information needed for a route to be compared to [`QueryDump`].
/// The main usage is to generate [`Report`]s with [`check`](#method.check).
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Compare {
    /// IP prefix propagated.
    pub prefix: IpNet,
    /// AS path for the propagation.
    pub as_path: Vec<AsPathEntry>,
    /// Recursion limit when checking against [`QueryDump`].
    /// Default to [`RECURSION_LIMIT`]
    pub recursion_limit: isize,
    /// [`Verbosity`] level when generating report.
    /// Default to [`Verbosity::ErrOnly`].
    pub verbosity: Verbosity,
}

impl Compare {
    pub fn new(prefix: IpNet, mut as_path: Vec<AsPathEntry>) -> Self {
        as_path.dedup();
        as_path.shrink_to_fit();
        Self {
            prefix,
            as_path,
            recursion_limit: RECURSION_LIMIT,
            verbosity: Verbosity::ErrOnly,
        }
    }

    /// Set `self.verbosity`.
    pub fn verbosity(self, verbosity: Verbosity) -> Self {
        Self { verbosity, ..self }
    }

    /// Create [`Compare`] from a line of table dump generated by `bgpdump`
    /// on a MRT file.
    pub fn with_line_dump(line: &str) -> Result<Self> {
        let (prefix, as_path, _, _) = parse_table_dump(line)?;
        Ok(Self::new(prefix, as_path))
    }

    /// Check `self` against RPSL policy `dump` and generate reports.
    /// Depending on which [`Verbosity`] `self.verbose` is set to,
    /// the reports have different levels of details.
    /// If [`Verbosity::ErrOnly`], stops at the first erroneous AS pair.
    pub fn check(&self, dump: &QueryDump) -> Vec<Report> {
        let mut reports = Vec::with_capacity(self.as_path.len() * 2);
        reports.extend(self.check_last_export(dump));

        // Iterate the pairs in `as_path` from right to left, with overlaps.
        let pairs = self
            .as_path
            .iter()
            .rev()
            .zip(self.as_path.iter().rev().skip(1));
        for (from, to) in pairs {
            if let (AsPathEntry::Seq(from), AsPathEntry::Seq(to)) = (from, to) {
                match self.check_pair(dump, *from, *to) {
                    r if r.is_empty() => (),
                    r => {
                        reports.extend(r);
                        if self.verbosity <= Verbosity::ErrOnly {
                            break;
                        }
                    }
                }
            } else {
                reports.push(Report::skip(SkipReason::AsPathPairWithSet(
                    from.clone(),
                    to.clone(),
                )));
            }
        }
        reports.shrink_to_fit();
        reports
    }

    pub fn check_last_export(&self, dump: &QueryDump) -> Option<Report> {
        match self.as_path.last()? {
            AsPathEntry::Seq(from) => self
                .get_aut_num_then(dump, *from, |from_an| {
                    self.check_export(dump, from_an, *from, None)
                })
                .or_else(|| self.success_report(|| SuccessType::ExportSingle(*from))),
            entry => self.skip_report(|| SkipReason::AsPathWithSet(entry.clone())),
        }
    }

    pub fn check_pair(&self, dump: &QueryDump, from: usize, to: usize) -> Vec<Report> {
        let from_report = self
            .get_aut_num_then(dump, from, |from_an| {
                self.check_export(dump, from_an, from, Some(to))
            })
            .or_else(|| self.success_report(|| SuccessType::Export(from, to)));
        let to_report = self
            .get_aut_num_then(dump, to, |to_an| self.check_import(dump, to_an, from, to))
            .or_else(|| self.success_report(|| SuccessType::Import(to, from)));
        [from_report, to_report].into_iter().flatten().collect()
    }

    pub fn get_aut_num_then<F>(&self, dump: &QueryDump, aut_num: usize, call: F) -> Option<Report>
    where
        F: Fn(&AutNum) -> Option<Report>,
    {
        match dump.aut_nums.get(&aut_num) {
            Some(aut_num) => call(aut_num),
            None => self.skip_report(|| SkipReason::AutNumUnrecorded(aut_num)),
        }
    }

    pub fn check_export(
        &self,
        dump: &QueryDump,
        from_an: &AutNum,
        from: usize,
        to: Option<usize>,
    ) -> Option<Report> {
        if from_an.exports.is_default() {
            return self.skip_report(|| SkipReason::ExportEmpty);
        }
        let mut aggregator = self.check_compliant(dump, &from_an.exports, to)?;
        if aggregator.all_fail {
            let reason = match to {
                Some(to) => MatchProblem::NoExportRule(from, to),
                None => MatchProblem::NoExportRuleSingle(from),
            };
            aggregator.join(no_match_any_report(reason).unwrap());
            Some(Report::Bad(aggregator.report_items))
        } else {
            self.skips_report(aggregator.report_items)
        }
    }

    pub fn check_import(
        &self,
        dump: &QueryDump,
        to_an: &AutNum,
        from: usize,
        to: usize,
    ) -> Option<Report> {
        if to_an.imports.is_default() {
            return self.skip_report(|| SkipReason::ImportEmpty);
        }
        let mut aggregator = self.check_compliant(dump, &to_an.imports, Some(from))?;
        if aggregator.all_fail {
            aggregator.join(no_match_any_report(MatchProblem::NoImportRule(to, from)).unwrap());
            Some(Report::Bad(aggregator.report_items))
        } else {
            self.skips_report(aggregator.report_items)
        }
    }

    pub fn check_compliant(
        &self,
        dump: &QueryDump,
        policy: &Versions,
        accept_num: Option<usize>,
    ) -> Option<AnyReportAggregator> {
        let mut aggregator: AnyReportAggregator = match self.prefix {
            IpNet::V4(_) => self.check_casts(dump, &policy.ipv4, accept_num),
            IpNet::V6(_) => self.check_casts(dump, &policy.ipv6, accept_num),
        }?
        .into();
        aggregator.join(self.check_casts(dump, &policy.any, accept_num)?);
        Some(aggregator)
    }

    pub fn check_casts(
        &self,
        dump: &QueryDump,
        casts: &Casts,
        accept_num: Option<usize>,
    ) -> AnyReport {
        let mut aggregator = AnyReportAggregator::new();
        let specific_cast = if is_multicast(&self.prefix) {
            &casts.multicast
        } else {
            &casts.unicast
        };
        for entry in [specific_cast, &casts.any].into_iter().flatten() {
            aggregator.join(self.check_entry(dump, entry, accept_num).to_any()?);
        }
        aggregator.to_any()
    }

    pub fn check_entry(
        &self,
        dump: &QueryDump,
        entry: &Entry,
        accept_num: Option<usize>,
    ) -> AllReport {
        let peering_report = match accept_num {
            Some(accept_num) => self
                .check_peering_actions(dump, &entry.mp_peerings, accept_num)
                .to_all()
                .map_err(|mut report| {
                    if self.verbosity == Verbosity::PerEntry {
                        report.push(ReportItem::NoMatch(MatchProblem::Peering));
                    }
                    report
                })?,
            None => None,
        };
        let filter_report = CheckFilter {
            dump,
            compare: self,
            verbosity: self.verbosity,
        }
        .check(&entry.mp_filter, self.recursion_limit)
        .to_all()
        .map_err(|mut report| {
            if self.verbosity == Verbosity::PerEntry {
                report.push(ReportItem::NoMatch(MatchProblem::Filter));
            }
            report
        })?;
        peering_report.join(filter_report).to_all()
    }

    pub fn check_peering_actions<'a, I>(
        &self,
        dump: &QueryDump,
        peerings: I,
        accept_num: usize,
    ) -> AnyReport
    where
        I: IntoIterator<Item = &'a PeeringAction>,
    {
        let mut aggregator = AnyReportAggregator::new();
        for peering_actions in peerings.into_iter() {
            aggregator.join(
                self.check_peering_action(dump, peering_actions, accept_num)
                    .to_any()?,
            );
        }
        aggregator.to_any()
    }

    pub fn check_peering_action(
        &self,
        dump: &QueryDump,
        peering_actions: &PeeringAction,
        accept_num: usize,
    ) -> AllReport {
        CheckPeering {
            dump,
            compare: self,
            accept_num,
            verbosity: self.verbosity,
        }
        .check(&peering_actions.mp_peering, self.recursion_limit)
        // Skipped.
        /* ?
        .join(self.check_actions(&peering_actions.actions)?)
        .to_all()
        */
    }

    /// We skip community checks, but this could be an enhancement.
    /// <https://github.com/SichangHe/parse_rpsl_policy/issues/16>.
    pub fn check_actions(&self, _actions: &Actions) -> AllReport {
        Ok(None)
    }

    pub fn goes_through_num(&self, num: usize) -> bool {
        self.as_path.iter().any(|p| p.contains_num(num))
    }
}

impl VerbosityReport for Compare {
    fn get_verbosity(&self) -> Verbosity {
        self.verbosity
    }
}

pub const MULTICAST_V4: Result<Ipv4Net, PrefixLenError> =
    Ipv4Net::new(Ipv4Addr::new(224, 0, 0, 0), 4);
pub const MULTICAST_V6: Result<Ipv6Net, PrefixLenError> =
    Ipv6Net::new(Ipv6Addr::new(0xff00, 0, 0, 0, 0, 0, 0, 0), 8);

/// Check if `prefix` is multicast.
pub fn is_multicast(prefix: &IpNet) -> bool {
    match prefix {
        IpNet::V4(prefix) => MULTICAST_V4
            .expect("MULTICAST_V4 is for sure Ok")
            .contains(prefix),
        IpNet::V6(prefix) => MULTICAST_V6
            .expect("MULTICAST_V6 is for sure Ok")
            .contains(prefix),
    }
}
