on:
  push:
    paths:
      - ".github/workflows/python.yml"
      - "**.py"
jobs:
  python:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          working-directory: rpsl_lexer/
      - run: |
          rye test
          rye format --check
        with:
          working-directory: rpsl_lexer/
