on:
  push:
    paths:
      - '.github/workflows/python.yml'
      - '**.py'
jobs:
  python:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd rpsl_lexer/
          python -m pip install --upgrade pip
          pip install black pytest pyparsing
          pytest
          black **.py --check
