on:
  push:
    paths:
      - '.github/workflows/rust.yml'
      - '**.rs'
      - '**Cargo.toml'
jobs:
  rust:
    name: Rust checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust registry and build artifacts
        id: cache-rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/cache/
            route_verification/target/
          key: ${{ runner.os }}-rust-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rust
      - run: |
          export CARGO_INCREMENTAL=1
          cd route_verification/
          cargo test --workspace
          RUSTFLAGS="-Dwarnings" cargo clippy --workspace
          cargo fmt -- --check
